conversejs/converse.js

locale/pl/LC_MESSAGES/converse.po

Thanks for Converse.js, Jan-Carel <3

Polish translation of version 0.8.6.

---

bower.json
main.js
non_amd.html

This closes issue #299, Update to latest jquery.browser as pointed
out by @le717

jquery.browser >=0.0.7 from master repo

---

locale/hu/LC_MESSAGES/converse.json
locale/hu/LC_MESSAGES/converse.po

Updated hungarian translation (0.8.8)

Updated hungarian translation (0.8.8)

---

converse.js
docs/CHANGES.rst
spec/xmppstatus.js
tests/main.js

It fixes the problem by calling sendPresence method instead of using it's own presence message.
Added a new test file, let me know if this should be instead inside of an already existing one.

Fix show online presence issue #305

---

converse.js
docs/source/development.rst

- Basic test if the given jid contains @
- use jid as name if undefined
This is just a follow up for having chats.open() API.

contacts.add API to register contacts

---

converse.js
docs/source/development.rst

Adding 'rooms' API

---

converse.js

Fixes #372

---

converse.js
spec/register.js

Added support to submit registration form as legacy besides xform
This probably fixes issue #370 where the server is accepting legacy forms as stated on the comments

Issue #370 registration fails

---

converse.js
docs/CHANGES.rst
src/templates/toolbar.html

Preparing future translation for this button

Add placeholder for 'Insert a smiley'

---

converse.js
docs/CHANGES.rst

wrong callback argument mapping in XmppStatus initialize: fullname is
null

Bugfix. fullname is null

---

docs/CHANGES.rst
locale/fr/LC_MESSAGES/converse.po

French Translation

---

docs/CHANGES.rst
sass/converse.scss
sass/variables.scss

Add a variable to build CSS with another path for the fonts
import added in  ``sass/converse.scss``: Undefined variable $font-path with ``make css``

CSS: Fonts Path: editable $font-path via sass/variables.scss

---

converse.js
docs/CHANGES.rst

add ``offline`` as possible case to enable translation

Offline Pretty Status

---

converse.js
docs/CHANGES.rst
docs/source/configuration.rst
main.js
non_amd.html
src/deps-full.js
src/deps-no-otr.js
src/deps-website-no-otr.js
src/deps-website.js
src/strophe.ping.js

Use modified StropheJS ping plugin (AMD support)
Add Ping functionality
Add Pong handler
Fix to issue #144

XEP-0199: XMPP Ping

---

converse.js
docs/CHANGES.rst
docs/source/configuration.rst

the Call button is visible but no action is done

MUC: missing toggle Call handler and function

---

locale/de/LC_MESSAGES/converse.json
locale/de/LC_MESSAGES/converse.po

Probably more to come when I start using MUC and other stuff, but this fixes a lot of mistakes in german and adds some translations.
Cheers

Improve de locale

---

locale/de/LC_MESSAGES/converse.json
locale/de/LC_MESSAGES/converse.po

My colleague @dino115 pointed these out.
Have a nice weekend :beers:

More small improvements to german locale

---

locale/de/LC_MESSAGES/converse.json
locale/de/LC_MESSAGES/converse.po

Small german locale improvements

---

src/templates/room_panel.html

Hides server label in room panel when input is hidden by hide_muc_server=true config.

Hide server label in room panel when input is hidden

---

converse.js
docs/CHANGES.rst
main.js
non_amd.html

user language detection in order to format date and time in correct locale

I18N: detect language for MomentJS

---

converse.js
docs/CHANGES.rst
docs/source/configuration.rst
src/templates/pending_contact.html
src/templates/requesting_contact.html

I don't know if it's really useful but it's there

Enhancement #394 Option to allow chatting with pending contacts

---

docs/CHANGES.rst
main.js
non_amd.html

Cleanup references to strophe.roster.js in non_amd.html and main.js

Cleanup references to strophe.roster.js

---

locale/pt_BR/LC_MESSAGES/pt_BR.js

Procurei pela tradução e não hávia encontrado a tradução dessa frase, por isso venho aqui propor esta melhoria.

Adicionando Tradução de palavra

---

locale/converse.pot
locale/en/LC_MESSAGES/converse.json
locale/en/LC_MESSAGES/converse.po

- fix incorrect string mapping in en locale

Fix translation error in en locale

---

locale/pl/LC_MESSAGES/converse.po

Polish translation updated. Thanks again for your fantastic software :+1:

Update of Polish translation to version 0.9.6.

---

locale/hu/LC_MESSAGES/converse.po

Added the remaining untraslated strings, and also fixed some mistakes in
the translated ones.

Updated Hungarian translation

---

locale/ru/LC_MESSAGES/converse.po

Still undone. Ready to continue.

Translation for Russian language updated.

---

converse.js
docs/CHANGES.md

When try to reconnect function reconnect() calls few times until reconnect or fail, optimization changes.

A cleaner reconnect timeout.

---

.gitignore

IntelliJ IDEA based IDE generated files.

Ignoring .idea

---

converse.js
locale/it/LC_MESSAGES/converse.json

If you use auto_login=true, when you logout, the main panel hang on loading.

logout if you are using auto_login=true

---

docs/CHANGES.md
src/converse-core.js

if you login with auto_login without a /resource,  resource for that jid will be 'null'

add random resource also for auto_login

---

docs/CHANGES.md
docs/source/configuration.rst
src/converse-core.js

Add synchronize_presence option

Add synchronize_presence option

---

docs/CHANGES.md
src/converse-core.js

If you click on icon-status xmpp, you are not able to change status

change xmpp status also on icon-status click

---

docs/CHANGES.md
locale/ru/LC_MESSAGES/converse.json
locale/ru/LC_MESSAGES/converse.po

Corrected spelling, punctuation and terminology.

---

locale/ru/LC_MESSAGES/converse.json
locale/ru/LC_MESSAGES/converse.po

More relevant wording
Spelling corrections

Clean up Russain translation

---

locale/ru/LC_MESSAGES/converse.json

Include notification strings into Russian translation

---

docs/CHANGES.md
src/converse-core.js

Fix for issue #648

---

docs/CHANGES.md
src/converse-controlbox.js

- [x ] Add a changelog entry for your change in `docs/CHANGES.md`

online users count issue-656

---

locale/pl/LC_MESSAGES/converse.po

Polish translation updated to the current master.

---

README.md

Update Jasmine link

---

locale/it/LC_MESSAGES/converse.json

First step for better italian

---

README.md
index.html

Update index.html with a link to an up-to-date version of the Roundcube plugin in addition to the previous PR that updated the README.

Update index.html with up-to-date Roundcube plugin too

---

locale/it/LC_MESSAGES/converse.po

Better Italian Translations, new step

Other italian fix

---

.gitignore
composer.json
docs/CHANGES.md

Hi,
This is a start point to create `composer.json` and add your package in packagist.org. If you accept this pull request and issue #755, you should create an account in packagist.org, submit a new package and wire github webhooks with packagist.
Unfortunately I can't do this for you, but I think it tooks only 10 minutes to accomplish this. If you create an username `jcbrand` in packagist, it will reflect name I wrote in composer.json. If you choose another name the composer.json should be updated.
Thank you!!

create composer.json to add this project in packagist.org

---

package.json

chore(package): update greenkeeper to version 4.1.0

---

locale/fr/LC_MESSAGES/converse.po

hi, here is my contribution to your project. It would be really easier to use a translation platform like https://hosted.weblate.org The dev make configuration himself.
I did not try to produce json file because I do not wish to install development tool in this computer, please make the transformation.

french translation review and completion

---

src/converse-mam.js

issue #486 fix

---

docs/CHANGES.md
src/converse-core.js

Presence priority NOT handled correctly #785

---

docs/CHANGES.md
docs/source/configuration.rst
spec/chatbox.js
src/converse-chatview.js
src/converse-core.js

This is a fix for issue #675 
This changes the time shown in the chatbox from a 12h time format to a 24h time format.

Changed to 24h time format

---

docs/CHANGES.md
spec/chatbox.js
src/utils.js

Fix #814: Images from URLs with query strings aren't being rendered.

---

css/converse.css
docs/CHANGES.md
sass/_controlbox.scss
sass/_minimized_chats.scss
sass/_roster.scss
src/templates/contacts_panel.html
src/templates/roster.html
src/templates/roster_filter.html
src/templates/toggle_chats.html
src/templates/trimmed_chat.html

As a follow-up to #695, this PR removes the last inline CSS styles so converse.js complies with strict [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) headers.
There still is one issue left with CSP, and that is one inline image, for which I will write a separate PR.
Executing `make clean dist check` seems to say that everything works fine:
```
...
Jasmine 2.5.2 finished in 32.581s
215 specs, 0 failures, 1 pending spec
```
There is a installation running this build, with CSP headers, [on jabber.at](https://jabber.at/conversejs/).
Please let me know if there is anything missing or want other improvements to the PR.

Csp compat 2

---

docs/CHANGES.md
docs/source/events.rst
spec/chatbox.js
src/converse-chatview.js
src/converse-core.js
src/converse-minimize.js
src/converse-rosterview.js
tests/utils.js

@jcbrand Hi! Because of PR turned out to be quite large, I decide to create separate issue (just for history purposes) for which I made these changes.

Inconsistent unread messages count updating #873

---

README.md

In Tiki, features are built-in (but optional) to avoid http://pluginproblems.com/

Tiki Wiki CMS Groupware now bundles ConverseJS

---

locale/it/LC_MESSAGES/converse.po

Updated the italian translation

Updated italian translation

---

Makefile

allow use of alternative port to for HTTPSERVE ( HTTPSERVE_PORT )

---

locale/ja/LC_MESSAGES/converse.po

Updated Japanese translation

---

src/converse-core.js
src/converse-muc.js

This helps translators reorder words in the string.

Always use formatting inside translatable strings

---

sass/_chatbox.scss

Image aspect ratio is changed in IE11. This PR fixes it.

fix image rendering in IE11

---

src/converse-core.js

locales_url should be relative

make locales_url a relative URL

---

demo/embedded.html

Get files from CDN for the embedded version

---

fullscreen.html

If "inVerse" is renamed to "fullscreen" then "inVerse" in the fullscreen.html file should be renamed to "Converse"?

Contributing 3 characters

---

docs/source/setup.rst

Hi,
just a minor extension to the docs.
Cheers and have a nice week
midzer

add another server which supports websockets

---

src/utils/core.js
src/utils/form.js

Fixed a bug which caused the list-multi form field e.g. for muc#roomconfig_presencebroadcast not being read and written correctly.

fix selected values in list-multi form fields

---

CHANGES.md
src/utils/core.js
src/utils/form.js

This PR changes my previous PR https://github.com/conversejs/converse.js/pull/1101. Otherwise it won't work in IE11.

Fix #1101 fo IE11

---

CHANGES.md
src/converse-chatview.js

Allow for shift-enter to insert newlines

---

src/converse-controlbox.js

Remove @locked_domain if it has been provided in the JID

---

README.md
index.html

All of them have been tested manually to see they still point to the same resource.

Fix some more links to use HTTPS.

---

src/converse-muc-views.js

Simplify an error message on MUC service shutdown

---

dist/converse-no-dependencies.js
dist/converse.js
docs/source/manual.rst
index.html
jslicenses.html
mockup/user-panel.html
spec/messages.js
src/utils/core.js

Sorry, but `</br>` is a no go for me.
I have put everywhere the same write version.

[BUGFIX] html linebreak

---

README.md
index.html

- reorder items in `index.html` and `README.md` equal
- add to feature common names e.g. HTTP Upload and Carbon

[DOC] update integration and features

---

CHANGES.md
src/utils/core.js

Deleolajide m4a webm support

---

spec/roomslist.js
src/templates/chatroom_details_modal.html
src/templates/chatroom_features.html

This now actually explains what it does.

Improve the moderated and not moderated explanations

---

webpack.config.js

Fixes improper dependency inclusion in headless build

Fix headless build webpack config

---

css/converse.css
dist/converse.js
sass/_chatbox.scss
spec/bookmarks.js
spec/chatbox.js
spec/chatroom.js
spec/http-file-upload.js
spec/notification.js
spec/roster.js
spec/spoilers.js
src/converse-bookmarks.js
src/converse-chatview.js
src/converse-controlbox.js
src/converse-minimize.js
src/converse-muc-views.js
src/converse-oauth.js
src/converse-profile.js
src/converse-rosterview.js
src/headless/converse-chatboxes.js
src/headless/converse-disco.js
src/headless/converse-muc.js
src/headless/utils/core.js
src/templates/alert.html
src/utils/html.js
tests/runner.js

Async await

---

CHANGES.md
src/converse-bookmarks.js

Please tell me if there's a better way to do that.
Still figuring out how tests work.
Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

Fix #1252, incorrect bookmark icon title

---

dist/converse.js
src/converse-message-view.js
src/templates/file_progress.html

Allow translation of “Uploading file:”

---

dist/converse.js
src/templates/user_details_modal.html

This depends on #1291, don’t mind the first commit.

Make user JID a link in user details

---

CHANGES.md
css/converse.css
sass/_chatbox.scss

fixing show_send_button:true issue.
This is my first pull request.If you find something wrong please delete this pull request.

show_send_button:true parameter not working for me.This pull is a fix for that issue

---

CHANGES.md
dist/converse.js
spec/http-file-upload.js
spec/messages.js
src/headless/converse-chatboxes.js

This fixes https://github.com/conversejs/converse.js/issues/1333.

don't send receipt requests in MUCs

---

css/converse.css
sass/_controlbox.scss
sass/_roster.scss

this should fix the remaining issues with the alignment of things in the controlbox

fixing some alignment issues in the sidebar

---

src/headless/converse-muc.js

Fix send_chat_state_notifications option for MUCs

---

sass/_core.scss
sass/_variables.scss

Concord theme: Fix owner badge color

---

CHANGES.md
COPYRIGHT
demo/embedded.html
demo/index.html
index.html
jslicenses.html
mobile.html

Change jcbrand to conversejs in releases urls

Change jcbrand to conversejs in releases urls

---

Makefile

Also include the unminified versions for people who wants to modify
them.

Makefile: Fix .min.css filename and include headless variant in assets

---

CHANGES.md
dist/converse.js
src/converse-muc-views.js

This will allow file upload by drag & drop also in MUCs

allow drag & drop also in MUCs

---

CHANGES.md
locale/lt/LC_MESSAGES/converse.po

Update Lithuanian (lt) translation

---

CHANGES.md

I hope this is what you meant :-)

Clarify section title

---

docs/source/plugin_development.rst

File has moved to ./headless/ subdir

Moved file

---

Makefile

Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>

Makefile: Add missing quote

---

src/headless/converse-chatboxes.js

For me file upload is not working in master. This seems to fix the problem

fix foreach in fileupload

---

docs/source/configuration.rst

Double "your"

---

CHANGES.md
fullscreen.html
package-lock.json
package.json
sass/_forms.scss

-had to change fullscreen.html (dist/converse.min.css,  dist/converse.min.js) to see changes

issue 1071 fixed : x clear cross now of same size as text

---

src/headless/converse-core.js

I am not sure if I can make tests for this, but this PR is an attempt to fix https://github.com/conversejs/converse.js/issues/1635
Works for me

Fix: use JID from credentials when credentials_url is set

---

CHANGES.md
src/converse-minimize.js

Shadow dom: TypeError: Cannot read property 'parentElement' of null caused by MinimizedChatsToggleView

---

CHANGES.md
src/converse-controlbox.js

Blacklisting converse-profile makes the control box totally blank

---

src/headless/package.json

Update headless package.json

---

CHANGES.md
src/headless/converse-mam.js

Process stanzas coming from mam one-by-one in order to fix processing of message receipts.

Process stanzas from mam one-by-one

---

CHANGES.md

I propose to fix the links in CHANGES.md.

fixed links in CHANGES.md

---

locale/id/LC_MESSAGES/converse.po

Add new indonesian language and fix error

---

CHANGES.md
docs/source/configuration.rst
sass/_core.scss
src/converse-muc-views.js

A replacement PR for https://github.com/conversejs/converse.js/pull/1755 because of conflicts

StartinBlox PR to fix issues

---

docs/source/configuration.rst

also  added recommendation to enable smacks when websockets are used.

Added examples for bosh & websocket connection to documentaton

---

CHANGES.md
sass/_controlbox.scss
spec/headline.js
src/headless/converse-headlines.js
src/templates/headline_list.html
src/templates/headline_panel.html

This PR is supposed to solve https://github.com/conversejs/converse.js/issues/1274

show headline messages in controlbox

---

CHANGES.md
webpack.common.js

Allow ignore bootstrap modules at build

---

CHANGES.md
src/headless/converse-chat.js

Fix https://github.com/conversejs/converse.js/issues/1896

Fix issue 1896

---

src/templates/oauth_providers.js

No change has been made in in `CHANGED.md` as the modification is pretty simple.
Rémy

Fix oauth provider template

---

CHANGES.md
src/converse-muc-views.js
src/templates/add_chatroom_modal.js

This PR fixes the rendering of `muc_roomid_policy_hint`.

fix rendering of `muc_roomid_policy_hint`

---

spec/xss.js
src/utils/html.js

Prevent tranforming malformed urls and urls with non-approved protocols into hyperlinks

---

src/templates/user_details_modal.js

Use <code> instead of <span> for fingerprint

---

src/components/adhoc-commands.js
src/utils/html.js

fixes for Ad-Hoc Commands

---

docs/source/configuration.rst

Fixes #2068: Edit prebind documentation example

---

CHANGES.md
src/converse-muc-views.js

Fixing the method name. Refs #2128
---

Allow users to send invitation by fixing method name, fixes #2128

---

src/headless/converse-core.js

The code this change refers to is already covered by the changelog in CHANGES.md.

Fix api.settings.update warning message

---

CHANGES.md
src/headless/converse-core.js

I'd like to add `CustomElement` to `converse.env`.

add CustomElement to env

---

CHANGES.md
spec/emojis.js
src/headless/converse-emoji.js

I found that emojis weren't rendered in case `use_system_emojis == false`. This PR fixes it.

fix emojis in case use_system_emojis == false

---

README.md

Corrects "**Disovering** Alternative XMPP Connection Methods" to "**Discovering** Alternative XMPP Connection Methods".

Update README.md - corrects typo

---

src/headless/converse-core.js

This fixes https://github.com/conversejs/converse.js/issues/2238.

fixes #2238 i18n not working reliably

---

spec/autocomplete.js
src/headless/utils/core.js

Allow mention autocomplete to trigger right after a new line

---

src/converse-omemo.js

**active** : #3DAC44
**inactive** : #F75681

#1829 add color for different omemo state

---

sass/_toolbar.scss
sass/_variables.scss

#2274 add background to send-button

---

CHANGES.md
src/headless/converse-emoji.js

This fix can only be tested in a plugin. The plugin and PR is currently running at https://conversejs.github.io/community-plugins

fix #2304 - Custom emojis (stickers) images not shown

---

CHANGES.md
docs/source/configuration.rst
spec/muc.js
src/converse-muc-views.js
src/headless/converse-muc.js

Update info messages setting

---

CHANGES.md
README.md
conversejs.doap

Project summary, including supported XEPs in a machine-readable format,
for automated listings, aggregation of XEP implementation status and
other nice things.
This list was simply scraped from the README and mangled into XML using
`csv2 | sed | 2xml` and amended with a few other details from e.g.
package.json and links on the website.
More info in [XEP-0453: DOAP usage in XMPP](https://xmpp.org/extensions/xep-0453.html).

Add Description Of A Project (DOAP) file

---

src/shared/styling.js

Fixes an endless loop

---

CHANGES.md
src/headless/converse-muc.js

The /nick command is not working in converse7. This PR aims to fix it.

fix /nick command not working

---

CHANGES.md
src/headless/utils/init.js

Adds hook to fetchLoginCredentials function to be able to modify the request, add headers, et. before sent.

Adds hook to fetchLoginCredentials function

---

src/plugins/muc-views/bottom-panel.js

Fix send button not working in a muc room

---

CHANGES.md
src/headless/shared/_converse.js

fixes issues with higher latency connections timing out fetchng stanzas
All tests appear to pass still, I did not add any additional as it was a value change not a new feature or similar. Hopefully that's ok. Also tests were with FF and Chromium as I don't have Chrome.

increase stanza timeout to 20s

---

CHANGES.md
src/shared/chat/emoji-dropdown.js
src/shared/chat/emoji-picker.js

About https://github.com/conversejs/converse.js/issues/2754
That's a try.
Could maybe help to think about a better fix.

Fixes #2754

---

docs/source/configuration.rst

Add "dracula" to the "theme" option documentation

---

src/plugins/controlbox/templates/controlbox.js

remove unnecessary }

---

conversejs.doap

---
Please let me know if any of these conditions need to be met by this PR.
xmpp.org now lists clients by their DOAP files (with image and platform infos), see https://xmpp.org/software/clients/

DOAP: Add logo and os/platform

---

docs/source/quickstart.rst

This is just a small documentation update: add ejabberd to the list, and also add home pages of all the three servers.

Add ejabberd and add XMPP servers homepages

---

.github/CONTRIBUTING.md

Fix https://github.com/conversejs/converse.js/issues/2972

Contributing typos

---

CHANGES.md
src/headless/plugins/muc/parsers.js
src/headless/plugins/muc/tests/messages.js

Select the immediate body, not the one in fallback.

---

CHANGES.md
src/plugins/bookmark-views/utils.js
src/plugins/roomslist/view.js

Fix muc icons not working due to incorrect target element.

---

src/shared/gif/utils.js

Fixes some GIF files failing with an `Invalid LZW code` error.

Fix some GIFs not rendering.

---

CHANGES.md
src/plugins/muc-views/modals/occupant.js
src/plugins/muc-views/modals/templates/occupant.js

muc: add a add to contacts button

---

docs/source/_templates/sponsors.html

image (logo of "c") is removed.
https://github.com/conversejs/converse.js/commit/c6bc5e14383900b5deab90792bb2684518ffd541

removing the entry for a removed sponsor image

---

CHANGES.md
src/i18n/pt_BR/LC_MESSAGES/converse.po

Just found some small orthographic errors while adding converse.js to a system I'm working on and fixed it.

Small pt_BR corrections

---

docs/source/builds.rst
docs/source/plugin_development.rst

This PR fixes some outdated documentation links.

Fix outdated documentation.

---

package-lock.json
src/headless/shared/parsers.js
src/headless/types/shared/parsers.d.ts
src/headless/utils/url.js
src/plugins/adhoc-views/templates/ad-hoc-command-form.js
src/plugins/adhoc-views/tests/adhoc.js
src/shared/styles/_core.scss
src/shared/styles/alerts.scss
src/shared/styles/forms.scss
src/shared/styles/themes/classic.scss
src/shared/styles/themes/concord.scss
src/shared/styles/themes/dracula.scss
src/templates/form_checkbox.js
src/templates/form_date.js
src/templates/form_input.js
src/templates/form_textarea.js
src/templates/form_url.js
src/templates/form_username.js
src/types/utils/html.d.ts
src/utils/html.js

Add support for general non-editable result XForm fields

---

src/plugins/muc-views/modals/templates/muc-config.js

Fix #3441: extra parameter to xFormField2TemplateResult

---

src/templates/form_checkbox.js

Field description was missing here.

Fix: desc was missing for input checkbox fields.

---

CHANGES.md

I really enjoyed using this project, nice work! Caught a couple of typos in the CHANGES.md though 😛

Update CHANGES.md, fix a typo

---

docs/source/troubleshooting.rst

fix minor typo and wording in troubleshooting.rst

---

CHANGES.md
src/i18n/ro/LC_MESSAGES/converse.po

- [ x] Add a changelog entry for your change in `CHANGES.md`
- [ x] When adding a configuration variable, please make sure to
- [ x] Please add a test for your change. Tests can be run in the commandline

Replace incorrectly twice-duplicated Romanian translated string with two correctly translated Romanian strings.

---

CHANGES.md
src/plugins/chatview/styles/index.scss
src/plugins/controlbox/styles/_controlbox.scss
src/shared/constants.js
src/types/shared/constants.d.ts

Increase the mobile cut-off width to 768 px

---

src/entry.js
src/headless/plugins/roster/contact.js
src/headless/shared/model-with-contact.js
src/headless/types/plugins/chat/model.d.ts
src/headless/types/shared/message.d.ts
src/headless/types/shared/model-with-contact.d.ts
src/plugins/chatview/chat.js
src/plugins/chatview/styles/chatbox.scss
src/plugins/chatview/templates/chat.js
src/plugins/rosterview/approval-alert.js
src/plugins/rosterview/index.js
src/plugins/rosterview/styles/approval-alert.scss
src/plugins/rosterview/templates/approval-alert.js
src/plugins/rosterview/tests/requesting_contacts.js
src/plugins/rosterview/utils.js
src/shared/styles/alerts.scss
src/shared/tests/mock.js
src/types/entry.d.ts
src/types/plugins/chatview/chat.d.ts
src/types/plugins/rosterview/approval-alert.d.ts
src/types/plugins/rosterview/templates/approval-alert.d.ts

Show approval alert in chats with requesting contacts.

---

src/headless/plugins/emoji/utils.js

Fix exception that occurs when optional cp attribute is missing

---

CHANGES.md
src/headless/plugins/pubsub/api.js

Use owner namespace to fetch configuration
