conversejs/converse.js

- Gruntfile.js
- Makefile
- Makefile.win
- docs/CHANGES.rst
- docs/source/development.rst
- package.json
Gruntfile now appends .cmd extension to r.js if platform is win32
Made touch-npm/bower grunt task/targets to be multiplatform (depends on node/grunt)
make -f Makefile.win to build on Windows
This is PR #301 with docs added and moved to a new branch.
> Added new Makefile.win, it only has dev/build/check targets

- converse.js
- src/templates/room_panel.html
hide_muc_server hides the input box but not the 'Server' label.
Of course, it's possible to patch the css for this purpose, but the gui should conform to the hide_muc_server directive.
Note : I didn't test it as I don't have time to setup a build environnement, but the change is simple enough.
> Hide 'Server' Label when hiding server input

- converse.js
I tried to use the `converse.plugins.extend` function but there was a bug. To check if a function was been added to the extended object, a `typeof key ===  'function'` was tested instead of `typeof value === 'function'`.
> Fix the plugin extend function

- converse.js
The storage id generated for the occupants of a chat room is the same for all chat rooms. The results is that all chat rooms fetches the same data and all chat rooms appear to have the same occupants.
This is fixed by adding the room jid in the generated id.
> Fix the ChatRoomOccupants storage id

- converse.js
When a state notification is received, a chat box is opened. If the notification is the result of the other person closing the chat box, it's annoying. User 1 closes a box, user 2 sees a box auto opening. User 2 closes the new box, user 1 sees a box auto opening. This has no end.
It's a known bug since there's a FIXME comment in the code.
I propose this fix: only open a chat box when the message has a body (i.e. a real message).
> Fix the known bug where a state notification reopens a chat box

- converse.js
Issues:
- when composing without interruption during a long time (longer than TIMEOUT.PAUSED), a `<paused>` state is sent. 
- after sending a message and after TIMEOUT.PAUSED, a `<paused>` state is sent.
These `<paused>` states shouldn't be sent. This bug comes from timeouts that are not correctly managed.
```
if (_.contains([ACTIVE, INACTIVE, GONE], state)) {
if (typeof this.chat_state_timeout !== 'undefined') {
clearTimeout(this.chat_state_timeout);
delete this.chat_state_timeout;
}
} else if (state === COMPOSING) {
this.chat_state_timeout = setTimeout(
$.proxy(this.setChatState, this), converse.TIMEOUTS.PAUSED, PAUSED);
} else if (state === PAUSED) {
this.chat_state_timeout = setTimeout(
$.proxy(this.setChatState, this), converse.TIMEOUTS.INACTIVE, INACTIVE);
}
```
When typing several …
> Fix a timeout bug in chat state notifications

- converse.js
- docs/CHANGES.rst
Fixes #374 
In RosterGroupView.addContact()
``` js
if (this.model.get('state') === CLOSED) {
if (view.$el[0].style.display !== "none") { view.$el.hide(); }
if (this.$el[0].style.display === "none") { this.$el.show(); } // HERE
} else {
if (this.$el[0].style.display !== "block") { this.show(); }
}
```
The problem is that on initial page load, the `<dt>` are hidden by a CSS rule but not directly in the style element. Therefore, the `style.display === "none"` test fails but the element is hidden.
A better way of checking visibility is to use jQuery's is(':visible') method :
``` js
if (!this.$el.is(':visible')) { this.$el.show(); }
```
I'll let you decide if the other visibility tests should be updated.
> Fix collapsed group visibility on reload

- converse.js
- docs/CHANGES.rst
This happens when you load a page with converse and do not login to
the chat. It can be tested in converse.org preserving logs while
navigating to another page.
Inside clearSession there's a call to roster which is not initalized
and also another one to controlbox.save which is not set so it fails
with an url error during sync.
> Fixed an error that appears when unload event is triggered

- converse.js
- docs/CHANGES.rst
- src/templates/login_panel.html
- src/templates/roster_item.html
This will allow to translate 'user@server' and 'password' in the login
screen and also in the roster-item tooltip, there's 'Name:' which can
now be translated
> Added login-panel placeholder and roster-item Name translations

- Makefile.win
I was getting the following error while running make all on my windows machine
"""
node_modules/.bin/bower install
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
make: *** [stamp-bower] Error 1
"""
This was resolved by adding the complete extension to the windows path.
> add .cmd extensions to makefile.win

- converse.js
- docs/CHANGES.rst
- docs/source/configuration.rst
Replace default language to autodetection if no i18n setting is set.
Add autodetection of the user language
default to locales.en if no matching found
> Language Detection

- locale/fr/LC_MESSAGES/converse.po
Excessive double quote in ./locale/fr/LC_MESSAGES/converse.po caused "make po" to fail:
./locale/fr/LC_MESSAGES/converse.po:286: end-of-line within string
> Excessive double quote in french translation file

- converse.js
Hey,
when upgrading my custom built version 0.9.3 to the current 0.9.5 (in order to use the new message archiving feature) converse stopped displaying any (sent and received) messages in the chat views.
When debugging the code, I found `first_msg_date` to be `null` and therefore the code trying to determine the insert position did nothing.
The situation is fixed in my PR by handling both `undefined` and `null` correctly.
I don't know why I get `null` from `$first_msg.data('isodate')` when you were getting `undefined`, maybe it is related to me receiving archived messages or using a slightly different jQuery version (1.10.2).
Cheers!
> Fix no messages being shown in chat 

- converse.js
- docs/CHANGES.rst
- src/templates/chatroom.html
- src/templates/room_item.html
Rooms with bullshit in name now working, yay!
Next: Submit `muc#roomconfig_roomname` on creation to persist full name on server.
> Fix #461: MUC working with spaces etc. in room names

- converse.js
- docs/CHANGES.rst
Fix [object Object] being shown as status when presence stanza with custom 'status' is received from other resource.
Cheers!
> Fix [object Object] being sometimes shown as status

- converse.js
Instead of __( it was _( caused [object Object] in more room info.
> Typo caused [object Object] in room info

- src/deps-no-otr.js
I had problems in the no-otr compilation.  I had to change the order of the parameters in this file.
> no-otr compilation issue: Utils is not defined

- converse.js
- docs/CHANGES.md
- docs/source/configuration.rst
As planned on issue #524 I have added this new parameter.
Minor fix: fixed confirm() dialog box when a request comes from someone not in your roster list
> Auto join on invite patch 1 (auto_join_on_invite new parameter)

- bower.json
- package.json
Fixed:
```
bower converse#*              mismatch Version declared in the json (0.10.0) is different than the resolved one (0.10.1)
```
> Bumped version to fix mismatch

- converse.js
- docs/CHANGES.md
When converse is first initialized `this.model.get('closed')` is undefined, at least with some configurations. This patch initializes the attribute with `!show_controlbox_by_default` if it is undefined.
> Fix for issue #261

- converse.js
- docs/CHANGES.md
When a chatbox is minimized and maximized, the scroll bar jumps back at the top of the conversation, forcing the user to scroll down again.
This pull request saves the position of the scroll bar on minimize, and restore it on maximize.
> Keep scroll position on minimize/maximize

- converse.js
- docs/CHANGES.md
This is an attempt (probably a bit ugly) to fix the problem described in #566 - when somebody talks to you, the opening chatbox steals the focus, which is extremely annoying.
Here is a quick explanation:
I noticed that the focus is happening in `ChatBoxView.show`, so I disabled it from here. However it's good to focus when the user open the chatbox manually. I noticed that when the chatbox is opened by a click from the user, the execution flows first through `ChatBoxViews.showChat`. Unfortunately from here I didn't find anyway to call `focus`... so instead I made this method trigger the `show` event with a parameter `focus` set to `true`. I'm not sure what the `callback` parameter was used for, so I left it intact. There is probably a cleaner way to pass the parameter to the event.
> Don't steal focus when chatbox is opened automatically

- non_amd.html
- src/converse-muc.js
- src/utils.js
- converse-muc.js was overriding the global `converse` variable
with undefined (the factory function doesn't return anything)
- `locales` was not defined in utils.js in non AMD (not passed in
the factory function)
Note: I'm not using any OTR related code, so I do know about that.
> Fix non_amd.html

- docs/CHANGES.md
- sass/_controlbox.scss
- sass/_roster.scss
- src/templates/add_contact_dropdown.html
- src/templates/controlbox_toggle.html
I am attempting to use Converse.js as a webclient for https://jabber.at. But we use [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) headers to protect us against any XSS attacks. Converse.js uses inline CSS in a few places, which is ignored on our page due to the CSP header.
This pull request replaces some minor inline CSS with CSS styles. This would improve compatibility with CSP headers at least far enough that users can log in, the roster works and chatting works. More work would need to be done, but I thought I'd start with something small. I'm willing to put further work into this if you are interested and we can get this merged.
There is a test that fails with these changes, ``spec/protocol.js:82`` and ``spec/protocol.js:86``, but manually testing …
> Csp compat

- README.md
The previous plugin developer is still running an ancient version of converse.js.  This updates the link to point to a fork that us running a current version of converse.js.
> Use roundcube plugin fork with current converse.js

- src/converse-dragresize.js
The ChatRoomView renderDragResizeHandles is only rendering the top resize handle (`<div class="dragresize dragresize-top"></div>`). the insert was only inserting the first child of the dragresize template, which has 3 children. Modified to insert the whole the div that the dragresize template gets inserted into.
> Render all drag resize handles in ChatRoomView

- src/converse-api.js
@jcbrand You reverted [parts of my non roster chat commit](https://github.com/jcbrand/converse.js/commit/25d9880f9edc301ce391459d4959dbb8ae0991ff#diff-7a8f4a801d017f221fa2ccba7b7ddcb6L109). Is there a reason for this?
This commit reapplies these parts. I need to be able to set contact attrs with `chats.open`. I use this to set the `fullname` which is missing if the contact is not in the roster.
> Allow setting contact attrs on chats.open

- docs/CHANGES.md
- spec/controlbox.js
- src/converse-core.js
This PR fixes the bug mentioned in #585. Bug is on adding contact say **Singhal@conversejs.org** after **singhal@conversejs.org**(which are both same) gets add to contact list. This behaviour is bug because singhal@conversejs.org and Singhal@conversejs.org both are technically same JID.  Hence converting the JID to lowercase anytime user add a contact will solve this issue.
@jcbrand
> Fixes the duplication bug in adding contact

- docs/CHANGES.md
- spec/chatbox.js
- src/converse-core.js
This PR fixes the bug mentioned in #628 
The bug was actually in assignment of `fullname` variable. It should always be set to `from`.
So what was happening `fullname` variable in private chat(message carbons enabled) was getting set to `this.get('fullname)'` which is actually not the correct `fullname` in this case and due to this variable is set, `_.isEmpty(fullname)` results into `false` and this operation `fullname = from;` fail to carry out.
Hence the perfect fix should be to just to initialise it first and then set it to `from` .
@jcbrand 
So to test I registered with two accounts on conversejs.org -
* singhal@conversejs.org
* anshul@conversejs.org.
In screenshots - First block is of singhal@conversejs.org and rest two are of anshul@conversejs.org(to test message carbons - two end …
> Fixes the bug in displaying chat status during private chat (Message carbons)

- docs/CHANGES.md
- spec/chatbox.js
- src/converse-chatview.js
This fixes the bug #628 . 
While writing from another device, logged in with the same JID, the current code shows a different user is typing. This commit fixes that to show status message "Typing from another device" and "Stopped typing on the other device" in those cases. 
It however leaves the previous behaviour unchanged in case of other users.
> Fixed typing status for typing from different device

- docs/CHANGES.md
- docs/source/configuration.rst
- src/converse-core.js
- src/converse-register.js
- src/templates/register_panel.html
- src/templates/registration_request.html
This is an implementation of the feature requested in #704 .
A new configuration variable `enable_default_domain` which when set to true, the registration form on initiation reads the domain from `default_domain_name` and fetches the registration form for the same. It doesn't allow the user to input the domain or cancel the fetched registration form by any means.
@jcbrand please review the codes, while I'm moving on to adding documentation for the added configurations, as well as updating changelog. I don't think any specific tests can be written for this because the behaviour is same as the mainline sequence of taking user input and fetching registraion form, except with forced event triggers.
> Implemented auto fetching of registration form for default XMPP domain

- docs/CHANGES.md
- docs/source/configuration.rst
- sass/_chatbox.scss
- sass/_variables.scss
- src/converse-chatview.js
- src/converse-core.js
- src/converse-headline.js
- src/converse-muc.js
- src/templates/chatarea.html
- src/templates/chatbox.html
Following changes creates a send button functionality at the bottom of chatbox. This is fix regarding the issue #682.
Following changes creates a new function in converse-chatview.js which handles event triggered on clicking the send button and rests are UI changes.
@jcbrand 
Please find the attached screenshot of this changes.
> Adds the send button at bottom of chatbox

- docs/CHANGES.md
- spec/chatbox.js
- src/converse-minimize.js
**Converse.js** already supports opening chat in minimized (trimmed) mode by specifying **minimized** attribute: **_converse.api.chats.open(jid, { minimized: true })**. But current implementation has incorrect behavior: if you pass **minimized: true** to **chats.open()**, then **both** normal and trimmed chatboxes will be opened. 
Proposed PR fixes this bug.
> support opening chat in minimized mode initially

- docs/CHANGES.md
- src/converse-minimize.js
@jcbrand Hi! I've made some research on this issue and it seems that possible solution is just **always** to save unread message count on server and fetch it when the page is (re)loaded (what has already been done).
> #567 Unreaded message count reset on page load 

- docs/CHANGES.md
- spec/chatbox.js
- src/converse-chatview.js
@jcbrand Hi! Solution turned out to be quite simple and I decide to make separate PR for fixing just this issue.
P.S. And, as I've already mentioned, I've found some inconsistent handling of new incoming messages that cause information about unread messages is out of sync in different parts of GUI. 
Problem scenario:
1. User opens chat
2. User scrolls up so that new message will be not visible
3. User receives message: indicator of 'new unread messages' are appeared at the bottom of chatbox
4. Roster view does not show unread messages count (**bug**)
5. User minimizes chatbox: there is no indicator of unread messages count (**bug**)
Now I continue working on it and (as soon as possible) will create separate PR.
> #591 Unread message counter is reset when the chatbox is closed 

- CHANGES.md
- src/converse-muc.js
As discussed in Issue #894 the methosSaveAffiliationAndRole compared strictly the bare jid bound to connection and the bare jid retrieved from XMPP presence message.
Fixed by converting both bare jid to lowe case.
> Converse ryzen 894

- CHANGES.md
- src/converse-muc.js
Allows plugins to override nickname when muc_nickname_from_jid is true.
> Fix regarding ChatRoomView.getDefaultNickName() and muc_nickname_from_jid

- locale/fr/LC_MESSAGES/converse.po
Simple locale fix, I guess I do not have to provide test and such.
Replacing « IM » with what is used in the rest of the file for « chat », and fixing a typo on « open » (which has to be translated by « ouvert », not « ouvrir », which means « to open ».
> IM is not a french word / « ouvrir » means « to open »

- docs/source/quickstart.rst
Changed the documentation to have the correct connection manager URL. If you try to use the old one, you'll get runtime JavaScript errors.
> Changed connection manager URL

- CHANGES.md
- src/templates/toggle_chats.html
toggle_chats.html template was broken in the construction of span.unread-message-count class attribute.
A missing `"` was causing the making of the DOM like so: 
`<span class="unread-message-count href=" #">...</span>`
Please note the `href=` class and the absence of the `href` attribute (see attachment).
> Fixed error building DOM toggle_chats.html span.unread-message-count class attribute

- docs/source/developer_api.rst
Was open instead of get in the example for get
> Fix mistyped example

- src/converse-chatboxes.js
I'm currently working on using Converse.js as components within a webpack based application. I'm going to share more results later.
I faced a problem, that `converse-chatboxes.js` references `Backbone.Overview` [here](https://github.com/cmrd-senya/converse.js/blob/c4c16d636d511570411826529c81c2c5d5fae74b/src/converse-chatboxes.js#L409). It is not a problem for the standard build because it somehow got resolved properly, but when I import Converse.js from a Webpack application as a library, this file don't load `Backbone.Overview` and I got `Backbone` defined, but `Backbone.Overview` is undefined. For me it works when I add `backbone.overview` reference to the dependency list of that module.
It seems that it doesn't change the usual build so I think it is safe to merge: it only makes …
> Add backbone.overview as a dependency for the chatboxes module

- CHANGES.md
- src/converse-muc.js
I recognized that https://github.com/jcbrand/converse.js/pull/977 does not work in MUCs. This PR fixes it.
> send emojis as unicode also in MUCs

- CHANGES.md
- docs/source/quickstart.rst
Documentation fix makes minified versions work across platforms - Addresses #1017
> Specify utf-8 charset in documentation so minified builds will work across platforms

- CHANGES.md
- docs/source/configuration.rst
- spec/chatbox.js
- src/converse-chatview.js
- src/converse-core.js
- src/converse-muc-views.js
- src/utils/core.js
This will replace geoURIs (e.g. from Convesations) by links to openstreetmap. Will also work the other way round.
If you like to use other websites instead of openstreetmap, this can be configured.
> replace geoURIs (e.g. from Convesations) by links to openstreetmap

- CHANGES.md
- docs/source/configuration.rst
- src/converse-rosterview.js
I'd like to remove the trailing "?" from the call to `xhr.open` in src/converse-rosterview.js when using `xhr_user_search_url` because of increased flexibility.
You might for example add more parameters to the API call (e.g. for supplying an API_KEY or similar). In this case, the already included "?" needs to be removed from the code.
> remove "?" from user-search-query

- Makefile
The 'dist/converse-no-dependencies-es5.js' rule is called
'dist/converse-no-dependencies-es2015.js'.
Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>
---
Do you still want a commit in `CHANGES.md`? This is just a quick fix in between a release :)
> Fix build targets in Makefile

- sass/_embedded.scss
This was rendering the content outside of the viewport, rendering Converse.js unusable.
> Remove position:relative in embedded CSS

- src/converse-disco.js
Converse forgot to add the wrapping query element, making the iq [invalid](https://pastebin.com/raw/T7h3FKHu).
Thanks to @lovetox for reporting this bug!
> Fix disco#info result stanza

- src/converse-chatview.js
- src/converse-roster.js
- src/templates/chatbox_head.html
The order of vCard nickname and fullname is subject to debate, but I just copied what was done elsewhere in Converse. The roster override though should imo always be first.
> Use the roster name or vCard nickname before falling back to vCard fullname or JID

- sass/_messages.scss
Currently multiple consecutive spaces or tabs were being transformed into a single space, rendering some ASCII art unreadable.  This patch fixes it by giving each message text the CSS behaviour of <pre/>.
> Keep multiple whitespace characters as is

- css/converse.css
- sass/_awesomplete.scss
- sass/_chatbox.scss
- sass/_chatrooms.scss
- sass/_controlbox.scss
- sass/_core.scss
- sass/_forms.scss
- sass/_headline.scss
- sass/_lists.scss
- sass/_messages.scss
- sass/_minimized_chats.scss
- sass/_roster.scss
- sass/_variables.scss
This will eventually allow client-side theming support.
Supersedes #1267.
> Switch from SASS variables to CSS custom properties

- dist/converse.js
- src/converse-chatview.js
- src/headless/converse-chatboxes.js
When one or more files are dropped on the textarea, they get uploaded or an error is printed if this isn’t possible.
There is also a fix to correctly displays an error when XEP-0363 isn’t supported by the server.
Fixes #1188.
> Upload files on drag-and-drop to the textarea

- dist/converse.js
- spec/chatbox.js
- spec/chatroom.js
- src/converse-message-view.js
Namely:
- Only match messages which start with exactly "/me ".
- Simplify the match, checking a string instead of a complex regex.
- Always remove the first four characters in the case of a match, to not
leave an extra leading space.
> Improve XEP-0245 support

- CHANGES.md
- docs/source/configuration.rst
- src/converse-notification.js
This PR introduces an option `notification_requires_interaction` which if enabled makes the notifications stay until explicitly dismissed by the user.
> added option "notification_requires_interaction"

- CHANGES.md
- docs/source/configuration.rst
- src/converse-notification.js
I propose that we add an option `notify_in_view` which defaults to `false`. Enabling it would make converse.js show notifications even if the tab of converse.js is shown to the user.
> new value 'all' for 'show_desktop_notifications'

- CHANGES.md
- css/converse.css
- dist/converse.js
- sass/_messages.scss
- sass/_variables.scss
- spec/http-file-upload.js
- spec/messages.js
- spec/omemo.js
- src/converse-message-view.js
- src/converse-omemo.js
- src/headless/converse-chatboxes.js
- src/headless/converse-muc.js
- src/templates/message.html
This is an attempt to implement XEP-0184: Message Delivery Receipts.
Hope you like it. Any feedback welcome.
> XEP-0184: Message Delivery Receipts

- CHANGES.md
- docs/source/configuration.rst
- src/converse-controlbox.js
- src/templates/login_panel.html
This PR introduces values `on` and `off` for the `trusted` option. This can be used to hide the "This is a trusted device" checkbox from the user.
> added values 'on' and 'off' for 'trusted' option

- CHANGES.md
- dist/converse.js
- docs/source/configuration.rst
- spec/presence.js
- src/headless/converse-core.js
This implements sending of idle presences according to XEP-0319: Last User Interaction in Presence. Using this, other clients can show at what time the user has been last active:
> Send presences according to XEP-0319: Last User Interaction in Presence

- CHANGES.md
- css/converse.css
- dist/converse.js
- sass/_controlbox.scss
- src/converse-controlbox.js
- src/converse-fullscreen.js
- src/headless/converse-core.js
- src/templates/controlbox.html
- src/templates/inverse_brand_heading.html
I propose to show a small text showing the version of converse.
> show version info in login dialog

- css/converse.css
- sass/_chatbox.scss
- sass/_chatrooms.scss
- sass/_controlbox.scss
- sass/_core.scss
- sass/_lists.scss
- sass/_messages.scss
- sass/_variables.scss
This is totally not inspired by https://discordapp.com/ :-° Hopefully
copyright doesn’t apply to a few CSS values, but this should be checked
before merging this PR.
Also I didn’t take much advantage of SCSS variables, so there is a lot
of duplication for colour values and such, this should be fixed before
this can be merged.
There is also no theme support in Converse yet, we may want to fix that
for people who prefer the old look.
Here is how it currently looks:
> Make Converse look more familiar to some users.

- CHANGES.md
- dist/converse.js
- src/headless/converse-muc.js
I see missing checkmarks in older muc messages. This tries to fix it.
> Fix missing checkmarks in old muc messages

- .travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
`sudo: false` is getting deprecated and support for it will soon be
removed entirely. They seem to be moving to using VMs entirely for their
service.
Converse doesn't seem to be using Travis' features extensively so I
don't think anything would break if we left the sudo clause as is, but it
will become useless in less than a month, (quite a tight timeline).
Signed-off-by: Maxime “pep” Buquet <pep@bouah.net>
> Remove `sudo: false` in .travis.yml

- CHANGES.md
- dist/converse.js
- spec/messages.js
- src/headless/converse-chatboxes.js
dwd discovered that receipts were being sent for carbons. This PR prevents it.
> prevent message delivery receipts for carbons and own

- CHANGES.md
- dist/converse.js
- src/headless/converse-chatboxes.js
I believe it's necesary to store receipts. Otherwise they might not reach the original sender (e.g. in case sender and receiver are not online at the same time). If they are stored in the archive, they will be retrieved later.
> set store hint on receipts and type='chat'

- CHANGES.md
- dist/converse.js
- spec/chatroom.js
- src/converse-muc-views.js
This implements the possibility to destroy a MUC.
> implement /destroy command in muc

- src/headless/converse-muc.js
A very simple change that fixes #1334.
Tested it for some time now, didn't notice any issue.
> Force avatar refetch if new hash received

- CHANGES.md
- dist/converse.js
- docs/source/configuration.rst
- src/converse-muc-views.js
I'd like to be able to limit the amount of room config options that are presented to the user. Therefore I created a new config option `roomconfig_whitelist`.
> new config option "roomconfig_whitelist"

- CHANGES.md
- dist/converse.js
- src/headless/converse-muc.js
Direct invite for a members only room must make sure that the invited user is added to the member list. This is currently not working.
This PR fixes it.
> fix direct invite for membersonly room

- CHANGES.md
- dist/converse.js
- src/templates/chatarea.html
- src/templates/chatbox.html
This asks screen readers to read every message received, and is mandatory for blind users to get notified of new messages.
> Add ARIA live region on chat-content

- CHANGES.md
- dist/converse.js
- docs/source/configuration.rst
- spec/muc.js
- src/converse-muc-views.js
I'd like to be able to selectively disable some muc moderator commands.
> muc moderator commands can be disabled selectively

- CHANGES.md
- dist/converse.js
- src/converse-muc-views.js
I believe it should be possible to change affiliation of non-occupants. Currently converse rejects this. This tries to fix it.
> fix moderator commands that change affiliation

- CHANGES.md
- dist/converse.js
- src/headless/converse-muc.js
Fixes #1414
This was broken in https://github.com/conversejs/converse.js/commit/a4d608dcdfe9c0d33ad65279369b0e6bd4a97def
Thanks for the hint @iNPUTmice
> Prevent duplicate messages on MUC join

- CHANGES.md
- dist/converse.js
- src/utils/html.js
As [per XEP-0004][1], the default `type` of data form fields is `text-single`, so a missing `type` attribute should not be treated differently.
This fixes handling of CAPTCHAs offered by ejabberd, which explicitly sets `type='text-single'`for [the `var='ocr'` field][2].
(For review, it might help to [ignore whitespace changes in the diff][3].)
[1]: https://xmpp.org/extensions/xep-0004.html#protocol-fieldtypes
[2]: https://xmpp.org/extensions/xep-0158.html
[3]: https://github.com/conversejs/converse.js/pull/1477/files?utf8=✓&diff=unified&w=1#diff-08112c1ee3f6b7f0cdbbae41576b6552
> Assume "text-single" as default form field type

- CHANGES.md
- spec/messages.js
- src/headless/converse-muc.js
Before the function `extractReference` in
`/src/headless/converse-muc.js` matched url and email.
Fix: https://github.com/conversejs/converse.js/issues/1327
> WIP attempt to fix issue #1327

- CHANGES.md
- dist/converse.js
- docs/source/configuration.rst
- src/converse-bookmarks.js
I'd like to be able to turn off converse.js' behaviour of autojoining MUCs bases on their bookmarks. This PR adds a new config option `muc_respect_autojoin` which allows this.
> make it configurable whether to respect autojoin

- CHANGES.md
- src/utils/html.js
Currently, in order for Converse.js to recognize a pasted URL as an
image, it must be an URL whose protocol is `https:` (`https` in the
URI.js library's notation). This is sensible, but means that any
non-HTTPS image URL is not recognized as a valid URL (and thus will not
be rendered inline, even if `show_images_inline` is set to `true`).
It is important to always check for HTTPS URLs when in a secure context
(i.e., the initial page load was requested via HTTPS) in order to ensure
that non-secured content does not mix with secured content. However, the
inverse is not true: if the original page was loaded over HTTP, then
enforcing HTTPS for images adds arguably no meaningful protection while
also breaking the `show_images_inline` feature for the edge cases where
Converse.js is deployed …
> Allow `http:` image URLs if Converse.js is loaded on an insecure origin.

- CHANGES.md
- dist/converse.js
- docs/source/configuration.rst
- src/converse-muc-views.js
I believe Converse shouldn't prompt for a reason if `auto_join_on_invite` is `true` because the inivted user won't see it anyway.
> Don't prompt for reason if auto_join_on_invite

- CHANGES.md
- dist/converse.js
- src/headless/converse-chatboxes.js
If I send a correction to Conversations the message will be rendered as a new message by Conversations. C seems to expect the message-id and the origin-id to be identical (I'm not 100% sure about it, but seems to work). This PR tries to fix it for conversejs.
> fix LMC with Conversations

- CHANGES.md
- src/converse-bookmarks.js
This is a fix for https://github.com/conversejs/converse.js/issues/1508
> Minimized bookmarked chatboxes should not be always maximized after page reload

- CHANGES.md
- dist/converse.js
- src/templates/add_contact_modal.html
I'd like to be able to manually entry a JID even if using xhr_user_search_url.
Therfore I propose to show the JID field.
> Allow manual entry of jid with xhr_user_search_url

- docs/source/style_guide.rst
Removed "an" in "When writing an a block such as an if or while statement,"
> Unnecessary word

- README.md
- docs/source/configuration.rst
- docs/source/developer_api.rst
- docs/source/other_frameworks.rst
- index.html
- mobile.html
Relates to issue #1565, "documentation mentions non-existent OTR support repeatedly".
Should i add an item to CHANGES.md for a doc-only change?
> Remove references to unsupported OTR encryption

- CHANGES.md
"- Properly handle message correction being received before the corrected message"
was there twice
Thanks for converse.js! :)
> Double entry

- CHANGES.md
- src/converse-chatview.js
Allows fancy things like taking a screenshot and pasting into chat.
Tested in Firefox 60.7 ESR
> Support sending files from clipboard

- CHANGES.md
- src/headless/converse-chatboxes.js
This fix forces Converse.js to respect auto_join_rooms and allow auto join room to occur with server-side generated random room names as required for XEP 0142 - workgroup queues
> Fix Issue #1679

- docs/source/configuration.rst
...since `locked_domain` needs to be "domain.tld" and can't be just `true`... or maybe `locked_domain` needs editing instead?
> Fix muc_domain link

- src/converse-oauth.js
Hey,
The login API format changed a while back, and the oauth module wasn't updated. This should fix it.
As the module is not being currently used, I didn't put anything in CHANGES.md (as it's mostly minor).
> Update Oauth login to current API format

- CHANGES.md
- src/headless/converse-chatboxes.js
Some clients don't use globally unique message ID's, but probably restart their sequence every time they (re)start. Since `correctMessage()` only checked for `id` and `from`, this would make completely unrelated messages from the same user overwrite each other's contents.
Tested that the fix prevents the problem and still properly handles actual corrections.
> Fix incorrectly detecting every message with a duplicate ID as correction

- CHANGES.md
- src/converse-notification.js
- src/headless/utils/core.js
This PR prevents notification sounds in case we receive a message delivery receipt only.
> don't notify if only message delivery receipt

- CHANGES.md
- docs/source/configuration.rst
- src/converse-chatview.js
- src/converse-message-view.js
- src/headless/converse-chatboxes.js
- src/headless/converse-muc.js
- src/templates/message.html
I'd like to be able to configure Converse for allowing edits of the message sent most recently.
This PR introduces a new config option `allow_message_corrections` which makes this possible.
> new config option: allow_message_corrections

- CHANGES.md
- src/converse-chatview.js
- src/headless/converse-chatboxes.js
I believe Converse should not allow editing of sent file upload messages, as this would only make sense if you actually upload another file. This PR prevents editing of sent file uploads.
> prevent message correction for files

- CHANGES.md
- sass/_chatbox.scss
- sass/_chatrooms.scss
- src/converse-dragresize.js
- src/converse-mouse-events.js
- src/converse-muc-views.js
- src/converse.js
- src/headless/converse-core.js
This adds the ability to resize the MUC-Member-List in all MUCs. The
MUC-Member-List can be scaled between 20% width of the MUC and 75% of
the MUC.
Everything was implemented as a plugin and can be disabled in the
converse.js-File. Furthermore this functionality can be enabled or
disabled through the allow_muc_roster_resizing parameter. Setting the
allow_muc_roster_resizing true will enable the feature. Setting it to
false will disable the feature.
> Add resize-functionality to MUC-Member-List

- src/headless/converse-mam.js
I think why do not come archives from group chats, and it turns out that you need to add "groupchat" in options. I spent half an hour searching in the documentation, and half an hour searching in the convers tests. And finally found in tests.
> Update converse-mam.js - add `groupchat` option in documantation

- CHANGES.md
- src/converse-notification.js
This PR makes desktop notifications clickable: A click on a desktop notification now opens the corresponding chat.
> notification is now clickable

- CHANGES.md
- src/headless/converse-bookmarks.js
I think converse should not log an error in case the user simply has no bookmarks.
> don't log error if user has no bookmarks

- CHANGES.md
- docs/source/configuration.rst
- src/converse-controlbox.js
This PR assures that the inital focus is on the jid field after the login-panel in the controlbox is rendered.
> focus now on jid field after controlbox is loaded

- CHANGES.md
- docs/source/configuration.rst
- locale/converse.pot
- sass/_modal.scss
- src/converse-muc-views.js
- src/templates/add_chatroom_modal.html
By this PR I'd like to introduce an option that defines a regular expression that a room id must satisfy to allow room creation. Server administrators may want to impose restrictions on the minimum and maximum length and the allowed character set allowed for room ids. Otherwise users might create rooms which are difficult to handle.
However, restricting that on the server only leads to bad UX as users might learn of the servers policy only after they have tried to create a room. Furthermore error messages from XMPP-servers might not be self-explanatory.
Therefore this option allows converse to already check the policy and disallow the user from even trying to entering/creating such a room.
> config option for roomid validation

- CHANGES.md
- src/converse-rosterview.js
- src/headless/converse-roster.js
This is a very much simplified version of https://github.com/conversejs/converse.js/pull/1634.
It does not do anything about the subscription of the self contact and also does not show the correct user status (online/away etc). It is however sufficient to safe your own contact to the roster and use it for whatever you want to do with it (might e.g. be useful to send data such as images from your computer to your smartphone).
The subscription of the self contact is always shown as "both" regardless of what is actually saved in the roster. This is of course not entirely correct but might nevertheless be acceptable taking into account that this solution only needs minimum changes to the code.
> A user can now add himself as a contact

- src/headless/converse-chatboxes.js
Previously, after increasing the msg_counter from 1 to 2, the window title would be set to "Messages (2)bla", and in the next iteration from 2 to 3 the regex wouldn't match anymore since it expects a space after the closing parentheses. This would spam up your window title with dozens of "Messages (x)" references.
Small enough that I thought it doesn't need a dedicated issue.
> Fix incrementMsgCounter cleaning up after itself

- src/templates/rooms_list.js
Add the space character that's missing between the toggle button and the `Open Groupchats` label (analogous to e.g. the `Bookmarks` list).
> Add missing space left to "Open Groupchats" label

- CHANGES.md
- spec/muc_messages.js
- src/utils/html.js
Third attempt at fixing this by modifying addMentionsMarkup. I now adjust reference start and end based on the count for prior occurences of the &_lt; and &_gt; characters.
I really dislike the start/end value system used in the references instead of a simple markdown like the colon delimters used with emojis. It reminds me of fixed length records used in very old school COBOL programming.
> fix #1963 - Mentions are visually incorrect when used in message replies

- CHANGES.md
- src/templates/emoji_picker.js
This PR fixes rendering of emojis in case `use_system_emojis == false`. Unfortunately I couldn't make it work using js-xss so I uses sanitize-html instead.
> make use_system_emojis==false work

- src/converse-oauth.js
The oauth_providers settings should be an array as a forEach is used on the settings later in the script.
No changelog entry has been made in CHANGES.md as the change is minor.
> oauth_providers settings should be an array

- src/converse-emoji-views.js
The current selector is very broad and may have undesired effects outside Converse. Used a more specific selector instead.
Also fixes textarea not focusing in some edge cases by adding stopPropagation and preventDefault.
> Updates textarea selector when applying focus after emoji selection

- CHANGES.md
- sass/_controlbox.scss
- sass/_variables.scss
Creates a separate `--controlbox-text-color` as suggested in https://github.com/conversejs/converse.js/issues/2101#issuecomment-650022225 and uses that to fix  #2101
*Ignore the fonts, disabled custom fonts in the browser due to rendering issues*
> Controlbox text color

- CHANGES.md
- spec/converse.js
- src/headless/converse-core.js
Conversejs is unable to start when a shadowRoot is provided as root in settings through converse.initialize. The first plugin calling settings.extend triggers an exception in https://github.com/conversejs/converse.js/blob/master/src/headless/converse-core.js#L665 because it tries to merge the whole initialization_settings defined by the keys in DEFAULT_SETTINGS. As shadowRoot elements have read-only attributes, when the merge tries to overwrite those attributes there's an exception raised .
`TypeError: Cannot assign to read only property 'mode' of object '#<ShadowRoot>'`
The proposed change here solves the issue extending and merging only the settings that  are relevant for the current plugin while keeping the overwrite from the settings passed in to Converse through converse.initialize …
> merge only relevant settings when calling api.settings.extend

- CHANGES.md
- src/headless/converse-bosh.js
After refactor in https://github.com/conversejs/converse.js/commit/16ca8044f814299b1b39d682678978f05d92b975#diff-ed7b4b012c33f7e3c09eaaf7df1bd15a function call fell out of sync.
> Fix BOSH session restore

- CHANGES.md
- src/headless/converse-core.js
I'd like to have `html` from `lit-element` in `converse.env`. Otherwise it does not seem to be possible to add toolbar-buttons from plugins. (See here: https://github.com/Polymer/lit-element/issues/390)
> add html to converse.env

- docs/source/configuration.rst
- spec/messages.js
- src/converse-chatview.js
- src/templates/directives/body.js
- src/utils/html.js
Example RegExp:
`/^https?:\/\/(?:www.)?(?:imgur\.com\/\w{7}|tradingview.com\/\w\/\w{8})\/?$/i`
Parsing function unit-tested here:
https://codepen.io/arielfuggini/pen/YzqVjyg
> adds setting to set non-image-extension image urls

- package-lock.json
- spec/omemo.js
- src/converse-omemo.js
- src/headless/converse-chat.js
- src/headless/converse-muc.js
- src/headless/utils/stanza.js
- Add hooks to the stanza parsers so that plugins can do additional parsing.
- Change ChatBox instance methods to functions and use them for stanza parsing.
- Move encrypt and decrypt messages to `converse.env.omemo`
Apparently, when receving a 1:1 carbon message, a device was wrongly created
for the contact's device list, instead of our own.
> Refactor OMEMO.

- src/converse-rosterview.js
- src/headless/converse-roster.js
The label group names in the roster are not translated. This PR aims to fix that.
> fix i18n of label group name

- src/headless/converse-core.js
Fixes
> FATAL: error: undefined .../converse.min.js:241 - TypeError: Promise.resolve is not a constructor
as noticed in the console
Small fix, changelog entry and test needed?
> Bugfix. Promise.resolve is not a constructor

- CHANGES.md
- src/modals/muc-list.js
The `updateRoomList` function gets called after each render, and the `onRoomsFound` handler calls `this.render()`. Looks like the problem is fixed when the `updateRoomList` only gets called on the `shown.bs.model` event. This is needed because the list will not update after re-opening the modal (it does not get destroyed on close).
Linked issue: #2092
> #2092 fixes room list update loop with locked muc domains

- spec/messages.js
- src/headless/converse-chat.js
- src/headless/converse-emoji.js
Unfortunately #1317 is back. This PR fixes it.
I didn't manage to fix the tests though. Maybe I'll find time to fix those tomorrow ...
> regression of #1317: Don't show errors for CSI messages

- CHANGES.md
- docs/source/configuration.rst
- src/components/message-history.js
- src/converse-chatview.js
Ideally it would be nice to have a setting to define the data sources and another to whitelist/blacklist the values. But I think the behavior in the PR is a good trade-off between flexibility and complexity. 
The reason behind having to define MUC role and MUC affiliation explicitly is to avoid showing `member` or `participant` for everyone in a MUC. So that only relevant affiliations and roles are displayed.
> Create hats from vcard conditionally

- src/i18n/index.js
fixed the formatting of the dayjs locale to allow the use of compound locale such as "pt_BR"
> #2290 fix dayjs locale format

- CHANGES.md
- src/converse-modal.js
This fix can be tested from the search plugin. The plugin and PR are currently running at https://conversejs.github.io/community-plugins
> fix #2307 - BootstrapModal no more accessible to plugins

- CHANGES.md
- src/components/message-history.js
Just for the record and future reference:
This change was attempted firstly by using a hook. Unfortunately `hook()` returns a promise which forces the call stack to be asynchronous all the way up to the `render()` method. Workarounds do exist but are not worth the effort. 
So, while the general direction of the project in this regard is to move towards the use of `hook()`, the solution agreed for this particular case is to allow `getHats()` to be overriden in the `overrides` object of plugins.
> Allow getHats method to be overriden

- CHANGES.md
- spec/muc_messages.js
- src/components/message.js
- src/headless/converse-chat.js
- src/templates/chat_message.js
When a message is corrected it gives the impression that it gets deleted, and the correcting message appears at the bottom of the chat history as if it was a new message that has been edited.
This pull request aims to fix the issue by keeping always the time of the original message while using the last edit timestamp to keep consistency with current behaviour.
> Fix message reorder issue after edit

- CHANGES.md
- src/components/emoji-picker.js
- src/templates/emoji_picker.js
Currently the `use_system_emojis` parameter is not honored by the emoji-picker. This PR fixes it.
> fix emoji-picker for use_system_emojis==false

- src/headless/utils/core.js
- src/utils/html.js
The "sendMessage" function of chatboxes throw an error in the headless build
> converse.env.utils.httpToGeoUri does not exist
Usage:
* src/headless/plugins/chat/model.js:797
* src/headless/plugins/muc/muc.js:946
> Move the httpToGeoUri util into the core

- src/shared/chat/emoji-picker.js
- src/shared/components/dropdown.js
When openening back and forth the same 2 MUCs, JS heap size goes up without being ever collected by the GC (even forced)
Browsers tested (archlinux):
- Chrome: 90.0.4430.93
- Firefox: 89.0.1
Those event listeners, if not removed properly, keep references to the chatboxes models everytime a room is open (in fullscreen mode)
> Fix stall document events

- CHANGES.md
- src/headless/plugins/smacks/utils.js
Sometimes, when registering, and when it tries to log you in, it tries to `get` something from the `shared_converse.session` object without it actually being there:
I noticed the expectation that I write a test, but I'm not 100% certain how to replicate it and therefore don't know how to test it. I doubt this works on all servers, or with all settings combinations, otherwise it would be noticed sooner. However, this is such a small change that hopefully the lack of a test can be allowed to slide.
Thanks!
> Ensure that the converse session is actually present

- CHANGES.md
- src/headless/utils/url.js
- [x ] Add a changelog entry for your change in `CHANGES.md`
> fix #2751 - Media not rendered when Converse runs in a browser extension

- CHANGES.md
- src/headless/plugins/mam/utils.js
- src/plugins/omemo/utils.js
With recent changes to handle decryption when reconnecting after receiving messages while offline, some MAM messages are still being lost. This PR causes code handling MAM results to wait until decryption and parsing is finishing before queuing the message in the chatbox.
Related to https://github.com/conversejs/converse.js/issues/2733
> Wait for parseMessages before queuing to UI

- src/plugins/muc-views/tests/muc-add-modal.js
As discussed in our meet, I changed `lounce` to `lounge`
> add-modal-test: replaced a mistyped jid

- src/plugins/muc-views/templates/add-muc.js
we need to not use the `converse-autocomplete` component when `locked_muc_domain` is `true`. A simple input as previously defined is ample in this case.
[locked-muc-domain](https://conversejs.org/docs/html/configuration.html#locked-muc-domain)
> add-muc: added the locked_muc_domain condition

- CHANGES.md
- docs/source/configuration.rst
Fix documentation about the enable_smacks option, which is set to true by default since version 6.0.0.
> Fix enable_smacks doc

- src/shared/gif/index.js
GCE comes before the frame data.  Save the delay to use in a future call to pushFrame.
Final frame needs to be pushed when EOF is encountered.  Intermediate frames are pushed when a new GCE is encountered.
> Save delay for future push.

- src/plugins/profile/templates/profile.js
Currently the logic of what’s show in the status is : 
1. vCard fullname if there is one
2. fall back to JID
This patch adds nickname between the two, so if the user has a vCard nickname but no fullname, it is shown instead of the JID : 
1. vCard fullname if there is one
2. vCard nickname if there is one
3. fall back to JID
> Show nickname in status if fullname is not provided

- CHANGES.md
- src/plugins/dragresize/index.js
This PR fixes stuttering of conversejs overlayed dragresize UI elements over the iframes on the parent page I've mentioned in issue #3156
> dragresize over iframe fix function concept

- CHANGES.md
- src/headless/plugins/muc/utils.js
This commit addresses issue #2716 where a chat opened via URL does not display when there is already an open chat. The changes ensure that the new chat overlaps the current conversation as expected.
I have made the necessary changes to fix the issue, but I was unable to add tests due to limited internet access and not being able to clone the repository. I would appreciate any assistance or guidance on how to proceed.
> Fix issue with chat display when opening via URL

- CHANGES.md
- docs/source/configuration.rst
- karma.conf.js
- src/plugins/muc-views/tests/occupants-filter.js
- src/plugins/roomslist/index.js
- src/plugins/roomslist/model.js
- src/plugins/roomslist/styles/roomsgroups.scss
- src/plugins/roomslist/templates/groups.js
- src/plugins/roomslist/templates/roomslist.js
- src/plugins/roomslist/tests/grouplists.js
- src/plugins/roomslist/view.js
This implements the proposal made in https://github.com/conversejs/converse.js/issues/3033.
When the `muc_grouped_by_domain` configuration option is set to `true`, chatrooms will be displayed by groups, based on their domain.
Note that this currently shows groups even when only one channel is being followed in the domain, unlike what was proposed in https://github.com/conversejs/converse.js/issues/3033.
This would require either moving all non-grouped channels before any groups, or adding an indentation or other visual indacator that channel are in groups, but the current version is fine for my use-case.
This is still missing:
Other possible changes:
- use `Strophe.getDomainFromJid` instead of `.split('@').at(-1)`
- put the code that generates `grouped_rooms` and `sorted_domains` in a …
> Muc domain grouping

- CHANGES.md
- src/headless/plugins/muc/muc.js
MUC informations are not correctly refreshed when another user/browser make changes.
This PR fix this bug.
To test:
> Open the same MUC room in 2 browers (with 2 accounts if possible, one moderator, the other not).
> Open/modify/save the room config form (change the title for example).
> Then, on the second browser, there is the notification for changes, but info are not refreshed. If you open the "room detail popup", old title still applies.
The bug was here:
```javascript
const codes = ['104', '170', '171', '172', '173', '174'];
if (sizzle('status', stanza).filter(e => codes.includes(e.getAttribute('status'))).length) {
```
The correct attribute to read is `code`, not `status`: https://xmpp.org/extensions/xep-0045.html#roomconfig-notify
> Fix: room information not correctly refreshed when modifications are made by other users

- CHANGES.md
- src/plugins/chatview/tests/styling.js
- src/shared/rich-text.js
- src/shared/styling.js
This fixes https://github.com/conversejs/converse.js/issues/3337.
Additionally, this considers the case of multiple empty lines in quotes, and correctly displaying empty lines not including trailing spaces.
> Correctly display multi-line nested quotes

- src/shared/chat/message-body.js
If this import is not indicated, the component is not registered.
So when it is called directly by the modal API's show method, the component is not found.
> Fix missing import when trying to display into modal popin an uploaded image.

- docs/source/configuration.rst
* custom default value is null.
* adding text to explain why custom category is disabled by default, and how to enable it.
> Fix custom emoji category documentation:

- src/shared/chat/templates/message.js
There is a regression in some rare case (comes with the new colorized avatars).
If for some reason we haven't loaded all occupants vcards, the code will load avatars, but not display them next to messages.
This PR fixes it: if the vcard is not on the contact model, we fallback to the message (as before, but code wasn't checking if the vcard is on the contact).
Note: this bug is visible in my project, were i have an optimization: i do not load all occupants vcards on join, if the occupant list is hidden (for performance reason). So, without this fix, message won't show the avatar, because `contact.vcard` is not set (we haven't called setVCardOnOccupant), but `message.vcard` is (thanks to setVCardOnMUCMessage).
> Fix regression for MUC message avatars.

- src/headless/plugins/muc/constants.js
- src/headless/plugins/muc/muc.js
- src/plugins/muc-views/modals/config.js
- src/plugins/muc-views/modals/templates/muc-config.js
- src/plugins/muc-views/tests/muc.js
- src/plugins/profile/modals/profile.js
- src/shared/tests/mock.js
When the MUC component offers no avatar field, the MUC room config save fails.
This PR fixes it.
> Fix: MUC config form fails when no image avatar field.

- docs/source/plugin_development.rst
Sorry, i was not able to test that the RST format is valid. As said on the Converse XMPP room, `make html` does not work, because of a pip dependency issue:
I go an error because sphinxcontrib.applehelp needs Sphinx 5. But the documentation won't compile with Sphinx5.
Similar issue here:
https://github.com/sphinx-doc/sphinx/issues/11890
One way to fix: find someone who has a working env, and copy all exact packages versions in the requirements.txt.
> Documentation: how to override custom elements.

- src/shared/chat/message-history.js
Seems this test was missing.
The bug was not visible in Converse v10.1.6 for an unknown reason. But it is with the current Converse master branch.
> Fix missing test case on dangling_moderation

- .eslintrc.json
- src/headless/shared/parsers.js
- src/headless/types/shared/parsers.d.ts
- src/utils/html.js
Trying to fix https://github.com/conversejs/converse.js/issues/3439
I am absolutly not sure that this fix is correct. I only tried to guess what you meant to write.
> Fix #3439: form field regression.

- src/i18n/converse.pot
- src/shared/chat/message.js
There was a label that was not localized: when a message is moderated, but there is no actor (which is allowed by XEP-0245), the label "A moderator" was hardcoded.
> Fix: missing localization for "A moderator" label.

- src/plugins/muc-views/templates/muc-sidebar.js
There was a typo. When less than 5 MUC occupants, the filter action should be removed, but it was not the case.
This was resulting in an empty filter element (see screenshot).
Note: perhaps we should always show the filter for MUCs? I'm aware that it is not very usefull when only few participants, but it would make the code simpler.
Currently, the 5 occupant limit is hard coded in several places. Could cause some troubles in the future.
> Fix typo: occupant filter is buggy in MUC with less than 5 occupants.

- CHANGES.md
- src/plugins/muc-views/templates/occupant.js
- src/plugins/muc-views/tests/occupants.js
The title was on the entire `<li>` elements, and was saying "click to mention". But the `<li>` includes also the avatar that will open the occupant modal, and not mention it.
> Fix: "Click to mention..." title was misplaced in MUC occupant list.

- CHANGES.md
- src/plugins/muc-views/modals/templates/occupant.js
There is no roster in singleton mode, so I think the "add to contact" button make no sense.
> Fix: removing the "add to contact" button in occupant modal in singleton mode

- src/shared/chat/message-actions.js
The renderActions method on messages was trying to guess if the message was the last one, to change the placement of the dropdown menu. It seems that this is no more needed (maybe thanks to the bootstrap v5 upgrade).
This commit removes this code, to always use "dropstart" class.
Note: this should complete @BetaRays PR: https://github.com/conversejs/converse.js/pull/3336
@BetaRays , could you test on your setup, and confirm that it is okay?
> Fix message dropdown menu placement

- CHANGES.md
- src/plugins/bookmark-views/components/templates/item.js
- src/plugins/chatview/templates/chat-head.js
- src/plugins/headlines-view/templates/feeds-list.js
- src/plugins/muc-views/templates/muc-head.js
- src/plugins/muc-views/templates/muc-password-form.js
- src/plugins/muc-views/templates/muc-sidebar.js
- src/plugins/profile/templates/profile.js
- src/plugins/roomslist/templates/roomslist.js
- src/plugins/rosterview/templates/roster.js
- src/shared/autocomplete/autocomplete.js
- src/shared/avatar/avatar.js
- src/shared/avatar/templates/avatar.js
- src/shared/chat/message-actions.js
- src/shared/chat/styles/message-actions.scss
- src/shared/chat/utils.js
- src/shared/components/dropdown.js
- src/shared/styles/lists.scss
- src/templates/form_input.js
I made an accessibility audit on my project. Part of the issues concern Converse.
Here are the required fixes. I have separated them in different commits, so we can discuss if necessary.
Here is the list of changes:
* adding role=button attribute on dropdown actions, for better
accessibility with screen readers.
* Autocomplete fields: shift+tab should always give focus to previous
focusable element, and tab should give the focus to next focusable
element if the input is empty.
* dropdown buttons: adding a "Menu" aria-label, and adding aria-hidden on icon.
* message actions: opacity:1 on focus.
* list-item-action: opacity:1 on focus, tabindex=0 to be focusable.
* adding aria-hidden="true" on fields with hidden-username class.
* Adding role="heading", aria-level="2" on userinfo, MUC title …
> Accessibility improvements

- CHANGES.md
- src/plugins/muc-views/sidebar.js
- src/plugins/muc-views/styles/muc-occupants.scss
- src/plugins/muc-views/templates/occupant.js
Here is a new hook, so that plugins can add an action menu on occupant list.
For example, i have plugins adding following entries:
By default, there is no action, so no dropdown.
@jcbrand , i know that you prefer have actions in the occupant modal. But in my case, I prefer having them here.
In the future, we could use the same hook for actions in the occupant modal.
And if an action should only be shown in the modal (or only in the occupant list), we could add some attributes to the buttons, so that we can filter them.
Let me know if this PR is ok for you. (no hurry, it can wait if you don't have the time for now).
> New "getOccupantActionButtons" hook, so that plugins can add actions on MUC occupants.

- CHANGES.md
- src/plugins/muc-views/templates/occupant.js
- src/plugins/muc-views/tests/occupants.js
By default, we take the first letter of all badge, and only display this letter (full badge name is set as title and aria-label for screen readers). If there is ambiguous letters, we use 2 (or 3, ... up to 4) letters.
> MUC occupants badges: displays short labels, with full label as title.

- CHANGES.md
- src/headless/plugins/emoji/utils.js
* Fix: trying to use an emojis with an uppercase letter breaks the message field.
* Fix: isOnlyEmojis vs uppercase letters.
* Fix: renaming getEmojisByAtrribute to getEmojisByAttribute.
> Fix emojis vs uppercase letters:

- src/plugins/muc-views/templates/message-form.js
When the toolbar was moved (commit f91d5e2c146b3d13e599c46b07ed1971cf94494e), the is_groupchat attribute was wronly computed.
> Fix regression:

- src/templates/form_checkbox.js
In the ConverseJS WIP, there is a bug for checkbox fields in room configuration form: if the label + description are too long, there is an extra line break:
This PR fixes this issue:
> Fix checkbox styling in forms.

- CHANGES.md
- src/plugins/roomslist/templates/roomslist.js
- src/plugins/roomslist/view.js
Fixes https://github.com/conversejs/converse.js/issues/3529.
- ~~When adding a configuration variable, please make sure to
document it in `docs/source/configuration.rst`~~
> Prevent duplication of text avatar into display name

- src/headless/plugins/bookmarks/plugin.js
- src/headless/plugins/muc/muc.js
- src/plugins/bookmark-views/index.js
- src/plugins/bookmark-views/tests/bookmarks.js
- src/plugins/bookmark-views/utils.js
- src/plugins/muc-views/modals/templates/muc-details.js
- src/plugins/muc-views/styles/muc-details-modal.scss
- src/plugins/muc-views/templates/muc-head.js
- src/plugins/muc-views/tests/muc-avatar.js
- src/plugins/roomslist/templates/roomslist.js
- src/plugins/roomslist/tests/roomslist.js
- src/types/plugins/bookmark-views/utils.d.ts
- Don't show the bookmarked icon in the header.
- Don't use the `name` from the bookmark, since Converse doesn't let you set the bookmark name and using it adds complexity.
- While refreshing the disco, set the MUC name
> Some MUC improvements

- CHANGES.md
- src/shared/styles/_core.scss
Fix auto zoom in  page in ios safari fullpage view mode when input message, it will result in a scroll bar present in x and y.
> Fix auto zoom in in ios safari fullpage view mode when input message

- CHANGES.md
- index.html
- src/plugins/register/index.js
The registration process is the main pain for regular users (just imagine explaining this to your relatives). 
The old compliance.conversations.im is not intended for users to pick a server. But this can be added to it with low efforts but this may be difficult to negotiate.
The Kaidan client uses the https://providers.xmpp.net/ as a categorized list of providers.
According to changelog the Converse used before some list of providers from the site #1206: 
> v4.0.1 (2018-09-19) Use https://compliance.conversations.im instead of dead link tot st https://xmpp.net
Unfortunately from the recommended A category only three servers doesn't require for a CAPTCHA which is annoying: https://jabber.fr, https://yax.im, https://xmpp.eath. And the BOSH is supported only by the jabber.fr. Basically we …
> index.js: change link to list of pulic XMPP providers for registrations

- docs/source/quickstart.rst
This adds a warning to the `Host it via your XMPP Server` part of the QuickStart guide, consistent with the warning in the `Using the CDN` section. A configuration example specific to ejabberd is also added to illustrate how to satisfy that warning.
fixes: #3772
> Adda a warning to quickstart about using version numbers when configuring xmpp server plugins.

- src/headless/plugins/bookmarks/model.js
- src/headless/plugins/disco/api.js
- src/headless/plugins/disco/entity.js
- src/headless/plugins/disco/types.ts
- src/headless/plugins/muc/muc.js
- src/headless/shared/api/send.js
- src/headless/types/plugins/disco/api.d.ts
- src/headless/types/plugins/disco/entity.d.ts
- src/headless/types/plugins/disco/types.d.ts
- src/headless/types/plugins/muc/muc.d.ts
And use it to set a lower timeout for disco info calls when joining a MUC.
Updates #3778
>  Add a timeout option to the `api.disco.refresh` function

- CHANGES.md
- docs/source/security.rst
This PR addresses a minor documentation formatting issue in the security.rst file. The change ensures proper underline length for section headers to match reStructuredText standards.
> Fix documentation formatting in security.rst
